version: "3"
services:
  db:
    image: postgres
    container_name: restrictify-postgres-dev
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restrictify
      - POSTGRES_USER=restrictify
      - POSTGRES_PASSWORD=restrictify
    networks:
      - restrictify-dev

  backend:
    container_name: restrictify-backend-service
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/backend/src
      - /app/backend/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://restrictify:restrictify@localhost:5432/restrictify
    networks:
      - restrictify-dev

volumes:
  pgdata:

networks:
  restrictify-dev:
