version: "3"
services:
  db:
    image: postgres
    container_name: easydev-postgres-dev
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=easydev
      - POSTGRES_USER=easydev
      - POSTGRES_PASSWORD=easydev
    networks:
      - easydev-dev

  backend:
    container_name: easydev-backend-service
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/backend/src
      - /app/backend/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://easydev:easydev@localhost:5432/easydev
    networks:
      - easydev-dev

volumes:
  pgdata:

networks:
  easydev-dev:
