apiVersion: skaffold/v3alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: aashish5355/auth
      context: ./services/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"

manifests:
  rawYaml:
    - ./infra/**/*.yaml
